global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  group_by: ['alertname', 'namespace']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: slack

receivers:
  - name: slack
    slack_configs:
      - channel: '#general'
        send_resolved: true
