version: '3.8'

services:
  flask_app:
    image: xyz010/ccbd_todo_app:latest
    container_name: todo-container
#    build: .
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - MONGO_HOST=db
      - MONGO_PORT=27017
    depends_on:
        - db
  db:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
